### ISSUE TITLE
New menu structure so people can actually find things

### ISSUE THREAD

**Issue by srees95** [NSAMR/uk.ac.nsamr.journal#391] opened 2018-03-25 13:13 UTC
Reorganise structure of 'contribute' section

Contribute (header) --> Author, Peer reviewer, Section editor --> page with all the relevant bits to each role

**Comment by DeckOfPandas** [comment] 2018-11-28 13:53
Duplicate of #385

**Closed as completed by DeckOfPandas** 2018-11-28 13:53 UTC
Labels: duplicate, v2
